### ISSUE TITLE
Command key not working on Mac+Chrome

### ISSUE THREAD

**Issue by mortenson** [ejarzo/abacusynth#1]
I believe the keycode used to detect the "command" key is wrong when using Mac and Chrome - it's currently `224` but I think it should check `91` as well, which is what https://www.toptal.com/developers/keycode says my command key is.

**Comment by ejarzo** [comment]
ahh thanks for the heads up! Made this change recently to match the controls with the plugin version and didn't realize chrome and firefox interpreted those keys differently.

**Comment by ejarzo** [comment]
Should be fixed now, also added back the Alt/Option key for the same function just in case...

**Comment by mortenson** [comment]
It works! Thanks @ejarzo , really fun project.
